---
title: "QBS 181 Final Project"
output:
  pdf_document: default
  html_document: default
date: "2025-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
trends <- trendsRaw <- read.csv("~/Desktop/archive/youtube_shorts_tiktok_trends_2025.csv")
hastags <- hastagsRaw <- read.csv("~/Desktop/archive/top_hashtags_2025.csv")
creators <- creatorsRaw <- read.csv("~/Desktop/archive/top_creators_impact_2025.csv")
monthly <- monthlyRaw <- read.csv("~/Desktop/archive/monthly_trends_2025.csv")
country <- countryRaw <- read.csv("~/Desktop/archive/country_platform_summary_2025.csv")

#head(trends)
#head(hastags)
#head(creators)
#head(monthly)
#head(country)
```

```{r}
# removing variables we aren't going to use

library(dplyr)

trends <- trends %>% 
  select(-views, -likes, -comments, -shares, -saves, -engagement_rate, -trend_label, -source_hint, -engagement_velocity, -dislikes, -comment_ratio, -share_rate, -save_rate, -like_dislike_ratio, -sample_comments, -engagement_total, -like_rate, -dislike_rate, -engagement_per_1k, -engagement_like_rate, -engagement_comment_rate, -engagement_share_rate, -author_handle)

#head(trends)
```

```{r}
# new csv from Gauri that has viral and non-viral coded
trendslabeled <- read.csv("~/Downloads/youtube_shorts_tiktok_trends_2025_labeled.csv")
```

```{r}
# removing unwanted variables
trendslabeled_new <- trendslabeled %>% 
  select(-views, -likes, -comments, -shares, -saves, -engagement_rate, -trend_label, -source_hint, -engagement_velocity, -dislikes, -comment_ratio, -share_rate, -save_rate, -like_dislike_ratio, -sample_comments, -engagement_total, -like_rate, -dislike_rate, -engagement_per_1k, -engagement_like_rate, -engagement_comment_rate, -engagement_share_rate, -author_handle)

#head(trendslabeled_new)
```

```{r}
# dataset for just viral videos
viral <- trendslabeled_new %>%
  filter(viral == 1)

#head(viral)

#dataset for just non-biral videos
nonviral <- trendslabeled_new %>%
  filter(viral == 0)

#head(nonviral)
```

```{r}
library(ggplot2)

# barchart to visualize distribution of genres in viral and non-viral vids
# y-axis by percentage to account for uneven # of uploads in each virality group

df_combined <- bind_rows(
  nonviral %>% 
    count(genre) %>% 
    mutate(pct = n / sum(n), type = "Non-viral"),
  
  viral %>% 
    count(genre) %>% 
    mutate(pct = n / sum(n), type = "Viral")
)

ggplot(df_combined, aes(x = genre, y = pct, fill = type)) +
  geom_col(position = "dodge") +
  labs(title = "Distribution of Genres: Viral vs Non-viral",
       x = "Genre",
       y = "Percentage",
       fill = "Virality") +
  scale_fill_manual(values = c("Viral" = "hotpink", 
                               "Non-viral" = "grey")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))

```

```{r}
# barchart to visualize distribution of categories in viral and non-viral vids
# y-axis by percentage to account for uneven # of uploads in each virality group

df_combined2 <- bind_rows(
  nonviral %>% 
    count(category) %>% 
    mutate(pct = n / sum(n), type = "Non-viral"),
  
  viral %>% 
    count(category) %>% 
    mutate(pct = n / sum(n), type = "Viral")
)

ggplot(df_combined2, aes(x = category, y = pct, fill = type)) +
  geom_col(position = "dodge") +
  labs(title = "Distribution of Categories: Viral vs Non-viral",
       x = "Category",
       y = "Percentage",
       fill = "Virality") +
  scale_fill_manual(values = c("Viral" = "hotpink", 
                               "Non-viral" = "grey")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))
```

```{r}
# ranking top categories in viral vids

category_counts_viral <- viral %>%
  group_by(category) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

category_counts_viral
```

```{r}
# ranking top genres that are going viral

genre_counts_viral <- viral %>%
  group_by(genre) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

genre_counts_viral
```

```{r}
# linegraph to compare upload counts by the hour in viral and non-viral vids

upload_counts_df <- as.data.frame(table(viral$upload_hour))
colnames(upload_counts_df) <- c("upload_hour", "count")
upload_counts_df$upload_hour <- as.numeric(as.character(upload_counts_df$upload_hour))
upload_counts_df$pct <- upload_counts_df$count / sum(upload_counts_df$count)
upload_counts_df$type <- "Viral"

upload_counts_df2 <- as.data.frame(table(nonviral$upload_hour))
colnames(upload_counts_df2) <- c("upload_hour", "count")
upload_counts_df2$upload_hour <- as.numeric(as.character(upload_counts_df2$upload_hour))
upload_counts_df2$pct <- upload_counts_df2$count / sum(upload_counts_df2$count)
upload_counts_df2$type <- "Non-viral"

df_combined <- rbind(upload_counts_df, upload_counts_df2)

ggplot(df_combined, aes(x = upload_hour, y = pct, color = type)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_continuous(breaks = 0:23) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Uploads by Hour: Viral vs Non-viral",
       x = "Upload Hour",
       y = "Percentage of Uploads",
       color = "Virality") +
  scale_color_manual(values = c("Viral" = "hotpink",
                                "Non-viral" = "grey")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
# barchart to compare average watch time (completion rate of vid) per day of the week

weekday_order <- c("Monday", "Tuesday", "Wednesday", "Thursday",
                   "Friday", "Saturday", "Sunday")

viral_sum <- viral %>%
  group_by(publish_dayofweek) %>%
  summarise(avg_watch = mean(avg_watch_time_sec, na.rm = TRUE)) %>%
  mutate(
    type = "Viral",
    publish_dayofweek = factor(publish_dayofweek, levels = weekday_order)
  )

nonviral_sum <- nonviral %>%
  group_by(publish_dayofweek) %>%
  summarise(avg_watch = mean(avg_watch_time_sec, na.rm = TRUE)) %>%
  mutate(
    type = "Non-viral",
    publish_dayofweek = factor(publish_dayofweek, levels = weekday_order)
  )

df_combined <- bind_rows(viral_sum, nonviral_sum)

ggplot(df_combined, aes(x = publish_dayofweek, 
                        y = avg_watch, 
                        fill = type)) +
  geom_col(position = "dodge") +
  labs(
    title = "Average Watch Time (sec) by Day of Week",
    x = "Post Day of Week",
    y = "Average Watch Time (sec)",
    fill = "Virality"
  ) +
  scale_fill_manual(values = c("Viral" = "hotpink", 
                               "Non-viral" = "grey")) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```
